controllers:
    resource: ../src/Controller/
    type: attribute

home:
    path: /home
    controller: App\Controller\HomeController::index

blog_list:
    path: /blog
    controller: App\Controller\BlogController::list

blog_show:
    path: /blog/{id}
    controller: App\Controller\BlogController::show
    requirements:
        id: '\d+'

contact:
    path: /contact
    controller: App\Controller\ContactController::index
